import Head from 'next/head';
import Basket from '../components/Basket';
import Header from '../components/Header';
import Landing from '../components/Landing';
import Tabs from '../components/Tabs';
import { getSession } from 'next-auth/react';
import type { Session } from 'next-auth';
import { GetServerSideProps } from 'next';

interface Props {
  session: Session | null;
}

function Home({ session }: Props) {
  return (
    <div>
      <Head>
        <title>Apple</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/apple.ico' />
      </Head>
      <Header />
      <Basket />
      <main className='relative h-[200vh] bg-background'>
        <Landing />
      </main>
      <section className='relative z-40 -mt-[100vh] min-h-screen bg-darkBackground'>
        <div className='space-y-10 py-16'>
          <h1 className='text-center text-4xl font-medium tracking-wide text-white'>
            New Promos
          </h1>
          <Tabs />
        </div>
      </section>
    </div>
  );
}

export default Home;

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
};
